[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
config = "0.14.0"
serde = { version = "1.0.209", features = ["derive"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
